### ISSUE TITLE
"Failed to start", Cytoscape 3.1.1 on OS X 10.8

### ISSUE THREAD

**Issue by rbedi** [keiono/cy-rest#11]
App "fails to start" according to cytoscape app-manager. Screenshot of app manager attached. 

OS X 10.8.3, Cytoscape 3.1.1. Tried both pre-alpha builds; neither works.

![screen shot 2014-08-15 at 4 20 31 pm](https://cloud.githubusercontent.com/assets/5823755/3940018/d2848906-24d2-11e4-8c1d-8ea55f3d984d.png)

**Comment by keiono** [comment]
Looks two jars with same App (cy-rest) are in _~/CytoscapeConfiguration/3/apps/installed_ directory.  Can you check that directory and remove cy-rest jars?  Then restart Cytoscape and install it again?

Thanks,
Kei

**Comment by rbedi** [comment]
Kei,
Even with only one (see screenshot attached), the exact same behavior occurs. 
Thanks,
Rishi
![screen shot 2014-08-18 at 3 17 58 am](https://cloud.githubusercontent.com/assets/5823755/3950155/ff7421c0-26c0-11e4-9bd2-81d330fddfe7.png)

**Comment by rbedi** [comment]
Works on my Ubuntu 13.04 Desktop install (same version of Cytoscape and the plugin), FYI.

**Comment by keiono** [comment]
Oh, it might be a Java version issue.  This App is compatible with Java 7 only, not Java 6.  I think Java 6 is still the default for Mac, and you need to install Oracle Java 7 when you try this app on Mac.

**Comment by rbedi** [comment]
Hm, I did in fact have Java 6 installed, so I went ahead and installed Java 7 - but that didn't seem to fix the problem. 

Here's what I have for "java -version":

```
Cytoscape_v3.1.1$ java -version
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)
```

When I run `./cytoscape.sh -R 1234`, I still get the same "Failed to start" error when I check the app manager, and a sample endpoint shows this:

```
Not Found
Resource identified by path '/v1/networks', does not exist.
Grizzly/2.3.3
```

**Comment by keiono** [comment]
Sorry for the confusion, but at this point, **this App is completely independent from the core features**.  This means you cannot use command line option to specify the port.  To use this app, just copy the jar to _installed_ dir, and restart Cytoscape.

To change port number, you just need to set a property **rest.port** in the _edit-->preferences-->properties__.

Default port for this APP is **1234**.

**Comment by rbedi** [comment]
Ah, got it - thanks for the clarification, I understand now. This time I just ran `./cytoscape.sh`, but in App Manager, it still says "Failed to start" for the cy-rest app, and testing an endpoint has the same does not exist behavior.

**Comment by keiono** [comment]
Hmm, that's strange.  Could you do the following?
1. Check ~/CytoscapeConfiguration/3/apps/installed/ directory and remove all cy-rest jar.
2. Start Cytoscape.
3. Open App Manager and make sure cy-rest does not exist.
4. Quit Cytoscape
5. Copy cy-rest jar file into the installed directory
6. Restart Cytoscape

If you cannot start it, can you see any error message in ~/CytoscapeConfiruration/3/framework-cytoscape.log?

**Comment by rbedi** [comment]
Ok, done - now it says "Installed" in app manager, but the endpoints still don't work & this is what I found in `framework-cytoscape.log`:

```
2014-08-18 13:15:04,344 [fileinstall-/Users/rishi/CytoscapeConfiguration/3/apps/installed] WARN  org.apache.felix.fileinstall - Error while starting bundle: file:/Users/rishi/CytoscapeConfiguration/3/apps/installed/cy-rest-0.2.0-08062014.jar
org.osgi.framework.BundleException: Activator start error in bundle org.cytoscape.rest.cy-rest [170].
    at org.apache.felix.framework.Felix.activateBundle(Felix.java:1951)
    at org.apache.felix.framework.Felix.startBundle(Felix.java:1822)
    at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:927)
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1244)
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1216)
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:505)
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:291)
Caused by: java.lang.UnsupportedClassVersionError: org/cytoscape/rest/internal/CyActivator : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at org.apache.felix.framework.ModuleImpl$ModuleClassLoader.findClass(ModuleImpl.java:1947)
    at org.apache.felix.framework.ModuleImpl.findClassOrResourceByDelegation(ModuleImpl.java:752)
    at org.apache.felix.framework.ModuleImpl.access$400(ModuleImpl.java:72)
    at org.apache.felix.framework.ModuleImpl$ModuleClassLoader.loadClass(ModuleImpl.java:1807)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at org.apache.felix.framework.ModuleImpl.getClassByDelegation(ModuleImpl.java:670)
    at org.apache.felix.framework.Felix.createBundleActivator(Felix.java:3808)
    at org.apache.felix.framework.Felix.activateBundle(Felix.java:1899)
    ... 6 more
```

**Comment by rbedi** [comment]
It seems that perhaps it only works with JDK version 1.7.0_51? That's what is running on my Ubuntu VM, but in OS X, I'm running JDK version 1.7.0_67. Does that correlate to the `Unsupported major.minor version 51.0` that shows up in the error log?

**Comment by keiono** [comment]
After you run Cytoscape from command line, by _cytoscape.sh_, could you try **info** command?
 Here is my output, a Mac running Java .67:

```
Cytoscape 3.1.1> info
Karaf
  Karaf version               2.2.11
  Karaf home                  /Applications/Cytoscape_v3.1.1/framework
  Karaf base                  /Applications/Cytoscape_v3.1.1/framework
  OSGi Framework              org.apache.felix.framework - 3.2.2

JVM
  Java Virtual Machine        Java HotSpot(TM) 64-Bit Server VM version 24.65-b04
  Version                     1.7.0_67
  Vendor                      Oracle Corporation
  Uptime                      1 hour 5 minutes
  Total compile time          12.337 seconds
Threads
  Live threads                62
  Daemon threads              54
  Peak                        64
  Total started               80
Memory
  Current heap size           151,322 kbytes
  Maximum heap size           13,981,184 kbytes
  Committed heap size         389,632 kbytes
  Pending objects             0
  Garbage collector           Name = 'PS Scavenge', Collections = 56, Time = 0.527 seconds
  Garbage collector           Name = 'PS MarkSweep', Collections = 3, Time = 0.493 seconds
Classes
  Current classes loaded      10,320
  Total classes loaded        10,321
  Total classes unloaded      1
Operating system
  Name                        Mac OS X version 10.9.4
  Architecture                x86_64
  Processors                  8
```

**Comment by rbedi** [comment]
It still seems to be finding Java 1.6:

```
Karaf
  Karaf version               2.2.11
  Karaf home                  /Applications/Cytoscape_v3.1.1/framework
  Karaf base                  /Applications/Cytoscape_v3.1.1/framework
  OSGi Framework              org.apache.felix.framework - 3.2.2

JVM
  Java Virtual Machine        Java HotSpot(TM) 64-Bit Server VM version 20.51-b01-457
  Version                     1.6.0_51
  Vendor                      Apple Inc.
  Uptime                      18.679 seconds
  Total compile time          11.264 seconds
Threads
  Live threads                34
  Daemon threads              26
  Peak                        35
  Total started               50
Memory
  Current heap size           57,000 kbytes
  Maximum heap size           15,711,616 kbytes
  Committed heap size         128,960 kbytes
  Pending objects             0
  Garbage collector           Name = 'ParNew', Collections = 46, Time = 0.201 seconds
  Garbage collector           Name = 'ConcurrentMarkSweep', Collections = 0, Time = 0.000 seconds
Classes
  Current classes loaded      8,318
  Total classes loaded        8,318
  Total classes unloaded      0
Operating system
  Name                        Mac OS X version 10.8.3
  Architecture                x86_64
  Processors                  8
```

... but when I run `java -version`:

```
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)
```

**Comment by keiono** [comment]
Probably **$JAVA_HOME** problem.  What's the output when you type

```
echo $JAVA_HOME
```

**Comment by rbedi** [comment]
Nothing - empty.

**Comment by keiono** [comment]
I see.  You need to set $JAVA_HOME when you use Oracle JVM.
In your .bashrc (or .zshrc if you use zsh), you need to add:

```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home
```

(This depends on your Java 7 binary location)

and the type

```
source ~/.bashrc
```

**Comment by rbedi** [comment]
That fixed it! Thanks so much for your help - and for the API docs, too!

**Comment by keiono** [comment]
Great!  I'll add note on this issue to the wiki, since default version of Java is still 6 on Mac and many Mac users may have same issue...
