### ISSUE TITLE
Deploy Complete REST API Documentation

### ISSUE THREAD

**Issue by rbedi** [keiono/cy-rest#12]
Hey,
Can I find API docs anywhere? Or even just a list of possible endpoints? 
Am happy to help generate one, if it doesn't exist, if you point me in the right direction, as well :)
thanks!
Rishi

**Comment by keiono** [comment]
Yes, this is one of the TODO items, but I've already setup a maven task for REST API document generator, and will be uploaded today.  (Although it's still incomplete.)

**Comment by keiono** [comment]
The API document will be deployed here:
- http://keiono.github.io/cy-rest/  (Still incomplete!)

**Comment by keiono** [comment]
First draft of API documents has been deployed.
