### ISSUE TITLE
UTF-8 non-English characters are not properly encoded in serializer

### ISSUE THREAD

**Issue by keiono** [keiono/cy-rest#23]
If table includes non-English UTF-8 chars, they cannot be decoded.  Need to specify encoding when returning non-English chars.

**Comment by bdemchak** [comment]
Can we go with Cytoscape’s UTF-8 encoding for now?

**Comment by keiono** [comment]
Everything is UTF-8 now.  The problem is, in some cases, it is not recognized as UTF-8.

**Comment by keiono** [comment]
Fixed.  In some cases, cy-rest serializes JSON from on-memory ByteArrayOutputStream.  And its toString() method is not smart enough to detect the correct encoding if data includes non-English chars.  This can be fixed by just passing optional encoding type parameter.  I've modified all toString() methods for ByteArrayOutputStream into toString("UTF-8") and this resolves this bug.
