### ISSUE TITLE
Get SUID list of networks; with GET parameters: Gives up too early

### ISSUE THREAD

**Issue by jbethune** [keiono/cy-rest#30]
Used URL:
http://example.com/v1/networks/ (docs: http://keiono.github.io/cy-rest/#-1099067042)
with GET parameters "column" and "query".

This request will fail (HTTP 500) if at least one of the network collections doesn't have a network table with the specified column, even though other network collections do have that column in their network tables.

I therefore suggest that network collections which don't have the specified column are ignored for the search.

**Comment by keiono** [comment]
Thanks for your report.  I'll cut a new release with the fix on Monday.
