### ISSUE TITLE
Make starting the cy-rest server more interactive

### ISSUE THREAD

**Issue by jbethune** [keiono/cy-rest#32]
If you want to run cy-rest on a different port, the current workflow of

> set a global Cytoscape property from Edit-->Preserences-->Properties... and add a new property port.number"

is rather obscure.

I suggest the following:
- Do not start the server automatically. I don't need it all the time and sometimes I have two instances of Cytoscape open and then I get the error message 

```
    javax.ws.rs.ProcessingException: Failed to start Grizzly HTTP server: Address already in use
```
- Don't put the global properties in the "cytoscape 3" namespace. Define a seperate "cy-rest" namespace for Edit-->Preserences-->Properties.
- Also make it possible to define the address to bind to. It would be cool if you could control cy-rest from a different computer. The address "localhost" makes this impossible (unless you SSH into the machine first).
- Define a management interface in the OSGi console:

```
    cy-rest start localhost 1234
    cy-rest start 192.168.1.1 1234
    cy-rest stop
    cy-rest query http://192.168.1.1/v1/networks
```

Where the last command only supports HTTP GET queries. This should be regarded mostly as a diagnostic tool and not as something to actually work with.
- Define a dialog in the Menu: Apps -> cyREST. Then a window should pop up where you can start and stop the server with parameters described in the previous bullet point. This is for the people who start Cytoscape without a visible OSGi console. The hostname and port fields can be prefilled from the global Cytoscape properties if they are set. If the user uses this method, you can save his choice of host and port as global Cytoscape properties.

**Comment by keiono** [comment]
The idea adding OSGi console commands sounds reasonable to me.  I'll add it to 1.0.0 release.

**Comment by bdemchak** [comment]
Careful, Kei ... let's talk about security ramifications of where this is
going ...

**Comment by keiono** [comment]
Barry, this feature is already a part of CyProperty and enable/disable service is also already a part of OSGi console function.  Essentially, this is just a syntax sugar for command line users.

**Comment by bdemchak** [comment]
Yeah … I’m less concerned about this, and more concerned about the consequences of supplying full path names for session load and store.

**Comment by keiono** [comment]
I see your point.  Actually, I missed the last one.

```
cy-rest query http://192.168.1.1/v1/networks
```

does not different from typing:

```
curl http://192.168.1.1/v1/networks
```

from command line.  And actually, it is more flexible than OSGi console because we can use all kinds of nice UNIX tools by piping the results.

What's the advantage for this? >jbethune

**Comment by jbethune** [comment]
You are right about curl being more powerful than my suggestion of `cy-rest query`. So just forget about it.

@bdemchak 

> Yeah … I’m less concerned about this, and more concerned about the consequences
> of supplying full path names for session load and store.

Are you refering to issue #33? Because I don't understand why are you are talking about sessions here. How are full path names a problem? Is it because the user could specify a remote path?

**Comment by keiono** [comment]
OK, then I'll add the setting part to the OSGi console.
