### ISSUE TITLE
Save and load sessions

### ISSUE THREAD

**Issue by jbethune** [keiono/cy-rest#33]
It should be possible to save and load sessions via cy-rest.
This could be especially handy when several sessions have to be created automatically.

**Comment by jbethune** [comment]
And I think this would be cool in combination with an IPython notebook because then you can later see which cytoscape session has been used for the notebook session.

**Comment by keiono** [comment]
Just started to implement the following new API for session:
- **GET /session?file=FILE_LOCATION** - save session into the specified file
- **GET /session/name** - returns current session name
- **POST /session?file=FILE_LOCATION** - Create session from file
- **DELETE /session** - Delete current session and start a new one

**Comment by keiono** [comment]
IPython Notebook idea sounds great.  I'll create a new notebook using this new API.
