### ISSUE TITLE
Add API for View objects

### ISSUE THREAD

**Issue by keiono** [keiono/cy-rest#35]
Need to support RESTful operations for View objects.  This is for setting/getting Visual Property values for the given view object.

**Comment by keiono** [comment]
This API should support batch update.

**Comment by keiono** [comment]
## Draft of View Object API

### For all Visual Property Values for a Graph Object
- GET /networks/NET_SUID/views/VIEW_SUID/nodes/NODE_VIEW_SUID
- GET /networks/NET_SUID/views/VIEW_SUID/edges/EDGE_VIEW_SUID
- GET /networks/NET_SUID/views/VIEW_SUID/nodes/NODE_VIEW_SUID/VISUAL_PROPERTY_NAME
- GET /networks/NET_SUID/views/VIEW_SUID/edges/EDGE_VIEW_SUID/VISUAL_PROPERTY_NAME

**Comment by keiono** [comment]
Here is the updated API:

## Get Current Visual Property Values for a View Object
- GET /networks/NET_SUID/views/VIEW_SUID/nodes/NODE_SUID
- GET /networks/NET_SUID/views/VIEW_SUID/edges/EDGE_SUID

The return value looks like this:

``` json
[
    {
        "visualProperty": "NODE_WIDTH",
        "value": 40
     }, ..., {}
]
```

## Directly Update View Object
- PUT /networks/NET_SUID/views/VIEW_SUID/nodes/NODE_SUID
- PUT /networks/NET_SUID/views/VIEW_SUID/edges/EDGE_SUID

And the BODY should have the following:

``` json
[
    {
        "SUID": 12345,
        "view": [
            {
                "visualProperty": "NODE_WIDTH",
                "value": 40
             }, ..., {}
        ]
    }, ... {}
]
```

With this API, users can update any Visual Property values for the view for multiple nodes/edges at once.

**Comment by keiono** [comment]
Query parameter has been added to selectively get Visual Property value from a view object. 
- GET /networks/NET_SUID/views/VIEW_SUID/nodes?visualProperty=VP_NAME
- GET /networks/NET_SUID/views/VIEW_SUID/edges?visualProperty=VP_NAME

For example, if you want to get node X position, use:

```
GET /networks/NET_SUID/views/VIEW_SUID/nodes?visualProperty=NODE_X_LOCATION
```

And this returns:

``` json
[ {
  "SUID" : 161,
  "view" : [ {
    "visualProperty" : "NODE_X_LOCATION",
    "value" : 42.974062556729564
  } ]
}, {
  "SUID" : 133,
  "view" : [ {
    "visualProperty" : "NODE_X_LOCATION",
    "value" : 296.2392603106358
  } ]
}, {
  "SUID" : 181,
  "view" : [ {
    "visualProperty" : "NODE_X_LOCATION",
    "value" : -343.0770086102626
  } ]
}, ...
]
```

**Comment by jbethune** [comment]
If we already have to provide a NODE_SUID or EDGE_SUID why do we also have to provide a SUID in the JSON payload?

```
    PUT /networks/NET_SUID/views/VIEW_SUID/nodes/NODE_SUID
    PUT /networks/NET_SUID/views/VIEW_SUID/edges/EDGE_SUID
```

and

```
[
    {
        "SUID": 12345,
        "view": [
            {
                "visualProperty": "NODE_WIDTH",
                "value": 40
             }, ..., {}
        ]
    }, ... {}
]
```

What does this SUID refer to?

And can you please regenerate the API documentation in HTML form with the new API endpoints?
