### ISSUE TITLE
Get network view as png: Returns mime type application/json instead of image/png

### ISSUE THREAD

**Issue by jbethune** [keiono/cy-rest#38]
The docs: http://keiono.github.io/cy-rest/#1288037935
The URL: GET http://example.com/v1/networks/networkId/views/viewId.png
The server replies with Content-Type: application/json but the content itself is a png image. The docs also say that something of Content-Type application/json will be returned.

In contrast, getting the _first_ network view as a png works fine http://keiono.github.io/cy-rest/#144494073

**Comment by keiono** [comment]
Fixed by the following commit:

https://github.com/keiono/cy-rest/commit/b1f5efc24bc5c46685111747441adac8aad90fd0
