### ISSUE TITLE
NetworkClient.get()

### ISSUE THREAD

**Issue by brownmk** [keiono/cy-rest#44]
line 148: return requests.get(self.__url + '/' + str(id) + '.json').json()
Does not seem to work.  networks/52.json does not seem to be supported by CyREST API.
Maybe change it into:
return requests.get(self.__url + '/' + str(id)).json()

**Comment by brownmk** [comment]
This is a question for py2cytoscape, file cyNetwork.py. Thanks

**Comment by brownmk** [comment]
Okay, I will post this to py2cytoscape instead.

**Comment by keiono** [comment]
This has been fixed in py2cytoscape 0.4.5.
